<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Magenheim.Core/Magenheim.Core.csproj" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <Compile Include="../../src/Magenheim.Runtime/Definitions/MagenheimDefinitionLoader.cs" Link="Runtime/MagenheimDefinitionLoader.cs" />
    <None Include="../../default-data/foundation.json" Link="foundation.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
