#!/usr/bin/env python3
"""Author in-place production actions for the Sulfurous Wastes Vent Spitter.

Requires assets/models/source/underworld-creature-vent-spitter.blend generated by
author-underworld-vent-spitter.py. Valheim owns world translation and combat authority;
this file owns physical pressure-sac telegraph, locomotion, spit recoil and reactions.
"""
from pathlib import Path
from math import radians, sin, pi
import bpy

ROOT=Path(__file__).resolve().parents[1]
BLEND=ROOT/'assets/models/source/underworld-creature-vent-spitter.blend'
if not BLEND.exists():
    raise RuntimeError(f'Missing source blend: {BLEND}')

bpy.ops.wm.open_mainfile(filepath=str(BLEND))
arm=bpy.data.objects.get('RIG_VentSpitter_HOST_QUADRUPED_EXT')
if not arm or arm.type!='ARMATURE':
    raise RuntimeError('Missing Vent Spitter HOST-QUADRUPED extension rig')

bpy.context.view_layer.objects.active=arm
arm.select_set(True)
bpy.context.view_layer.update()

ACTIONS={
    'Idle':48,
    'PressureIdle':64,
    'Walk':32,
    'Scuttle':20,
    'TurnLeft':24,
    'TurnRight':24,
    'Charge':36,
    'Spit':18,
    'Recoil':22,
    'Bite':18,
    'Hit':16,
    'Stagger':28,
    'Death':52,
}
LEGS=('FL','FR','HL','HR')
SEGS=('Upper','Lower','Hock','Foot')

def action_fcurves(act):
    legacy=getattr(act,'fcurves',None)
    if legacy is not None:
        return list(legacy)
    curves=[]
    for layer in act.layers:
        for strip in layer.strips:
            for bag in getattr(strip,'channelbags',()):
                curves.extend(bag.fcurves)
    return curves

def reset():
    for p in arm.pose.bones:
        p.rotation_mode='XYZ'
        p.rotation_euler=(0,0,0)
        p.location=(0,0,0)
        p.scale=(1,1,1)

def begin(name):
    full='VentSpitter_'+name
    old=bpy.data.actions.get(full)
    if old:
        bpy.data.actions.remove(old)
    act=bpy.data.actions.new(full)
    act.use_fake_user=True
    if arm.animation_data is None:
        arm.animation_data_create()
    arm.animation_data.action=act
    reset()
    return act

def key(bone,frame,rot=None,loc=None,scale=None):
    p=arm.pose.bones.get(bone)
    if p is None:
        raise RuntimeError(f'Missing Vent Spitter animation bone {bone}')
    if rot is not None:
        p.rotation_euler=tuple(radians(v) for v in rot)
        p.keyframe_insert('rotation_euler',frame=frame,group=bone)
    if loc is not None:
        p.location=loc
        p.keyframe_insert('location',frame=frame,group=bone)
    if scale is not None:
        p.scale=scale
        p.keyframe_insert('scale',frame=frame,group=bone)

def gait(name,end,amp,body_amp):
    begin(name)
    for frame in range(1,end+1,4):
        phase=2*pi*(frame-1)/max(1,end-1)
        for tag in LEGS:
            opposed=tag in ('FR','HL')
            swing=sin(phase+(pi if opposed else 0))
            key(tag+'_Upper',frame,(amp*swing,0,0))
            key(tag+'_Lower',frame,(-amp*.72*swing,0,0))
            key(tag+'_Hock',frame,(amp*.88*swing,0,0))
            key(tag+'_Foot',frame,(-amp*.28*swing,0,0))
        breathing=sin(phase*2)
        key('Spine',frame,(body_amp*breathing,0,0))
        key('Chest',frame,(-body_amp*.55*breathing,0,0))

begin('Idle')
for frame,value in ((1,0),(13,2.2),(25,0),(37,-2.2),(48,0)):
    key('Chest',frame,(value,0,0))
    key('Neck',frame,(-value*.45,0,0))
    key('Jaw',frame,(max(0,value)*.6,0,0))
    key('Sac',frame,scale=(1+value*.008,1+value*.012,1+value*.010))

begin('PressureIdle')
for frame,weight in ((1,0),(16,.55),(32,1),(48,.55),(64,0)):
    key('Sac',frame,scale=(1+weight*.16,1+weight*.22,1+weight*.18))
    key('Throat',frame,scale=(1+weight*.10,1+weight*.18,1+weight*.12))
    key('Chest',frame,(-4*weight,0,0))
    key('Jaw',frame,(10*weight,0,0))

gait('Walk',32,18,2.2)
gait('Scuttle',20,31,4.8)

for name,sign in (('TurnLeft',1),('TurnRight',-1)):
    begin(name)
    for frame,weight in ((1,0),(8,1),(16,1),(24,0)):
        key('Chest',frame,(0,0,sign*14*weight))
        key('Neck',frame,(0,0,sign*18*weight))
        key('Head',frame,(0,0,sign*12*weight))
        outer='FR' if sign>0 else 'FL'
        inner='FL' if sign>0 else 'FR'
        key(outer+'_Upper',frame,(24*weight,0,0))
        key(inner+'_Upper',frame,(-12*weight,0,0))

# Pressure charge is the defining tell: the reservoir and throat visibly inflate before release.
begin('Charge')
for frame,weight in ((1,0),(9,.35),(20,.78),(30,1),(36,1)):
    key('Sac',frame,scale=(1+weight*.36,1+weight*.48,1+weight*.40))
    key('Throat',frame,scale=(1+weight*.18,1+weight*.30,1+weight*.22))
    key('Chest',frame,(-8*weight,0,0))
    key('Neck',frame,(-10*weight,0,0))
    key('Jaw',frame,(7*weight,0,0))
    for tag in ('FL','FR'):
        key(tag+'_Upper',frame,(18*weight,0,0))
        key(tag+'_Hock',frame,(-21*weight,0,0))

# Spit violently compresses the sac through the throat into a wide mouth opening.
begin('Spit')
for frame,sac_scale,throat_scale,jaw,chest in (
    (1,1.34,1.22,8,-7),
    (5,1.46,1.32,18,-12),
    (9,.78,.82,42,16),
    (13,.90,.92,22,8),
    (18,1,1,0,0),
):
    key('Sac',frame,scale=(sac_scale,sac_scale,sac_scale))
    key('Throat',frame,scale=(throat_scale,throat_scale,throat_scale))
    key('Jaw',frame,(jaw,0,0))
    key('Head',frame,(-jaw*.22,0,0))
    key('Chest',frame,(chest,0,0))

begin('Recoil')
for frame,weight in ((1,0),(5,1),(11,.55),(17,.20),(22,0)):
    key('Chest',frame,(18*weight,0,0))
    key('Spine',frame,(-11*weight,0,0))
    key('Neck',frame,(-13*weight,0,0))
    key('Head',frame,(-8*weight,0,0))
    for tag in ('FL','FR'):
        key(tag+'_Upper',frame,(32*weight,0,0))
        key(tag+'_Lower',frame,(-28*weight,0,0))
        key(tag+'_Hock',frame,(18*weight,0,0))

begin('Bite')
for frame,jaw,neck,chest in ((1,0,0,0),(5,34,-12,-5),(9,-8,18,9),(13,7,7,3),(18,0,0,0)):
    key('Jaw',frame,(jaw,0,0))
    key('Head',frame,(neck*.42,0,0))
    key('Neck',frame,(neck,0,0))
    key('Chest',frame,(chest,0,0))

begin('Hit')
for frame,roll in ((1,0),(5,12),(10,-5),(16,0)):
    key('Chest',frame,(0,0,roll))
    key('Head',frame,(0,0,roll*.65))

begin('Stagger')
for frame,roll,pitch in ((1,0,0),(7,24,-13),(15,-16,15),(22,8,-7),(28,0,0)):
    key('Chest',frame,(pitch,0,roll))
    key('Spine',frame,(-pitch*.6,0,-roll*.5))
    key('Head',frame,(pitch*.45,0,roll*.6))
    for tag in LEGS:
        key(tag+'_Upper',frame,(abs(roll)*.36,0,0))

begin('Death')
for frame,roll,drop in ((1,0,0),(14,18,-.03),(28,52,-.11),(40,80,-.20),(52,88,-.25)):
    key('Pelvis',frame,(0,0,roll),loc=(0,0,drop))
    key('Spine',frame,(8 if roll else 0,0,roll*.55))
    key('Chest',frame,(14 if roll else 0,0,roll*.72))
    key('Neck',frame,(20 if roll else 0,0,-roll*.16))
    key('Head',frame,(24 if roll else 0,0,-roll*.12))
    key('Sac',frame,scale=(1,1,1))
    for tag in LEGS:
        key(tag+'_Upper',frame,(min(44,roll*.48),0,0))
        key(tag+'_Hock',frame,(-min(52,roll*.58),0,0))

# Contract gates.
for name,end in ACTIONS.items():
    act=bpy.data.actions.get('VentSpitter_'+name)
    if not act:
        raise RuntimeError(f'Missing Vent Spitter action {name}')
    act.frame_start=1
    act.frame_end=end
    curves=action_fcurves(act)
    if not curves:
        raise RuntimeError(f'Vent Spitter action {name} has no curves')
    for fc in curves:
        for point in fc.keyframe_points:
            point.interpolation='BEZIER'
        if 'pose.bones["Root"]' in fc.data_path and 'location' in fc.data_path:
            raise RuntimeError(f'Vent Spitter action {name} illegally animates Root.location')

for name in ('Walk','Scuttle'):
    act=bpy.data.actions['VentSpitter_'+name]
    paths={fc.data_path for fc in action_fcurves(act)}
    for tag in LEGS:
        for seg in SEGS:
            if f'pose.bones["{tag}_{seg}"].rotation_euler' not in paths:
                raise RuntimeError(f'{name} missing {tag}_{seg} articulation')

charge_paths={fc.data_path for fc in action_fcurves(bpy.data.actions['VentSpitter_Charge'])}
for bone in ('Sac','Throat'):
    if f'pose.bones["{bone}"].scale' not in charge_paths:
        raise RuntimeError(f'Charge does not physically inflate {bone}')

arm.animation_data.action=None
arm['production_contract']='production-creature-r2'
arm['authored_actions']=','.join('VentSpitter_'+name for name in ACTIONS)
arm['animation_fidelity']='pressure-sac inflation tell; throat transfer; violent compression spit; foreleg recoil brace; compact geothermal quadruped locomotion'
sc=bpy.context.scene
sc['magenheim_authored_actions']=arm['authored_actions']
sc['magenheim_skinning']='rigid-segment-weighted'
bpy.context.preferences.filepaths.save_version=0
bpy.ops.wm.save_as_mainfile(filepath=str(BLEND),compress=True)
print(f'Authored {len(ACTIONS)} Vent Spitter production actions into {BLEND}',flush=True)
