"""Author palette profiles for modifications of native Valheim armour donors.
No mesh construction: runtime clones donor equipment and retains meshes, skinning and cloth.
Legacy procedural armour sources remain archived for provenance only.
"""
from pathlib import Path
import sys
ROOT=Path(__file__).resolve().parents[1]
PALETTES={'sporeweave':(.64,.9,.7),'palewater':(.68,.9,1.),'emberiron':(.9,.62,.4),'rimeward':(.72,.85,1.),'stoneanchor':(.72,.7,.82),'defiant':(1.,.72,.45)}
TARGET=ROOT/'src/Magenheim.Runtime/UnderworldDonorArmourProfiles.g.cs'
text='// Generated by tools/author-underworld-donor-armour.py. Donor geometry is retained.\nusing System;\nusing UnityEngine;\nnamespace Magenheim.Runtime;\ninternal static class UnderworldDonorArmourProfiles\n{\n    internal static Color Tint(string modelId)\n    {\n'
for key,rgb in PALETTES.items():
 text+=f'        if(modelId.StartsWith("underworld-armor-{key}-", StringComparison.Ordinal)) return new Color({rgb[0]}f,{rgb[1]}f,{rgb[2]}f,1f);\n'
text+='        throw new InvalidOperationException("Unknown native armour palette: " + modelId);\n    }\n}\n'
if '--check' in sys.argv:
 if not TARGET.is_file() or TARGET.read_text(encoding='utf-8')!=text: raise SystemExit('Native armour profiles are stale; run this authoring script.')
 print('PASS: six palettes cover 24 native donor armour pieces; procedural geometry is not admitted.')
else:
 TARGET.write_text(text,encoding='utf-8');print('AUTHORED: native donor armour palettes; no mesh generation.')
