#!/usr/bin/env python3
"""Author in-place production actions for the Sulfurous Wastes Basalt Crawler.

Requires assets/models/source/underworld-creature-basalt-crawler.blend generated by
`author-underworld-basalt-crawler.py`. Valheim owns world translation; this file authors
low-crawler deformation, guard mechanics, strikes, ram telegraph and reactions only.
"""
from pathlib import Path
from math import radians, sin, pi
import bpy

ROOT=Path(__file__).resolve().parents[1]
BLEND=ROOT/'assets/models/source/underworld-creature-basalt-crawler.blend'
if not BLEND.exists(): raise RuntimeError(f'Missing source blend: {BLEND}')
bpy.ops.wm.open_mainfile(filepath=str(BLEND))
arm=bpy.data.objects.get('RIG_BasaltCrawler_HOST_LOW_CRAWLER')
if not arm or arm.type!='ARMATURE': raise RuntimeError('Missing Basalt Crawler HOST-LOW-CRAWLER rig')
bpy.context.view_layer.objects.active=arm; arm.select_set(True); bpy.context.view_layer.update()

ACTIONS={'Idle':48,'Scuttle':28,'TurnLeft':24,'TurnRight':24,'AttackLeft':22,'AttackRight':22,'FrontStrike':20,'Guard':32,'Ram':30,'Hit':16,'Stagger':30,'Death':56}
LEGS=tuple(f'{s}{i}' for s in ('L','R') for i in (1,2,3)); SEGS=('Upper','Lower','Foot')

def reset():
    for p in arm.pose.bones:
        p.rotation_mode='XYZ'; p.rotation_euler=(0,0,0); p.location=(0,0,0); p.scale=(1,1,1)
def action(name):
    a=bpy.data.actions.get('BC_'+name) or bpy.data.actions.new('BC_'+name); a.use_fake_user=True
    if arm.animation_data is None: arm.animation_data_create()
    arm.animation_data.action=a; reset(); return a
def key(bone,frame,rot=None,loc=None):
    p=arm.pose.bones[bone]
    if rot is not None: p.rotation_euler=tuple(radians(v) for v in rot); p.keyframe_insert('rotation_euler',frame=frame,group=bone)
    if loc is not None: p.location=loc; p.keyframe_insert('location',frame=frame,group=bone)

# Dense armored breathing: plates remain visually stable while protected body and mandibles move.
action('Idle')
for f,v in ((1,0),(13,2.2),(25,0),(37,-2.2),(48,0)):
    key('Body',f,(v,0,0)); key('Head',f,(-v*.45,0,0)); key('Mandible_L',f,(0,0,v*1.4)); key('Mandible_R',f,(0,0,-v*1.4))

# Low alternating-tripod scuttle. L1/R2/L3 oppose R1/L2/R3 and all three leg stages deform.
action('Scuttle')
for f in range(1,29,3):
    phase=2*pi*(f-1)/27
    for tag in LEGS:
        opposed=tag in ('R1','L2','R3'); s=sin(phase+(pi if opposed else 0))
        key(tag+'_Upper',f,(25*s,0,0)); key(tag+'_Lower',f,(-19*s,0,0)); key(tag+'_Foot',f,(11*s,0,0))
    key('Body',f,(2.5*sin(phase*2),0,0)); key('Abdomen',f,(-1.8*sin(phase*2),0,0))

# Heavy turns pivot the shell and exaggerate outside-front reach; left/right are true mirrors.
for name,sgn in (('TurnLeft',1),('TurnRight',-1)):
    action(name)
    for f,w in ((1,0),(8,1),(16,1),(24,0)):
        key('Body',f,(0,0,sgn*15*w)); key('Head',f,(0,0,sgn*11*w)); key('Brow',f,(0,0,sgn*8*w))
        outer='R1' if sgn>0 else 'L1'; inner='L1' if sgn>0 else 'R1'
        key(outer+'_Upper',f,(sgn*28*w,0,0)); key(outer+'_Lower',f,(-sgn*20*w,0,0)); key(inner+'_Upper',f,(-sgn*12*w,0,0))

# Lateral attacks commit body/head/mandible and same-side front/mid legs instead of floating jaws.
for name,sgn in (('AttackLeft',-1),('AttackRight',1)):
    action(name)
    side='L' if sgn<0 else 'R'
    for f,w in ((1,0),(6,.55),(11,1),(16,.45),(22,0)):
        key('Body',f,(0,0,sgn*17*w)); key('Head',f,(0,0,sgn*25*w)); key('Brow',f,(0,0,sgn*12*w))
        key('Mandible_'+side,f,(0,0,sgn*30*w)); key(side+'1_Upper',f,(18*w,0,0)); key(side+'2_Upper',f,(-12*w,0,0))

# Frontal strike lifts the brow just enough to expose the face, then snaps mandibles forward.
action('FrontStrike')
for f,b,h,m in ((1,0,0,0),(5,-10,-5,18),(10,8,14,-24),(15,3,5,-8),(20,0,0,0)):
    key('Brow',f,(b,0,0)); key('Head',f,(h,0,0)); key('Mandible_L',f,(0,0,m)); key('Mandible_R',f,(0,0,-m))
    for tag in ('L1','R1'): key(tag+'_Upper',f,(-h*.55,0,0)); key(tag+'_Lower',f,(h*.4,0,0))

# Guard physically shutters the recessed face behind the articulated brow and braces front legs.
action('Guard')
for f,w in ((1,0),(8,.65),(14,1),(25,1),(32,0)):
    key('Brow',f,(24*w,0,0)); key('Head',f,(-10*w,0,0)); key('Body',f,(-5*w,0,0))
    for tag in ('L1','R1'): key(tag+'_Upper',f,(22*w,0,0)); key(tag+'_Lower',f,(-27*w,0,0)); key(tag+'_Foot',f,(13*w,0,0))

# Ram is in-place: rear compression -> brow/foreleg brace -> impact posture -> recoil. Runtime moves the creature.
action('Ram')
for f,rear,fore,brow,body in ((1,0,0,0,0),(7,28,-16,10,-9),(13,-24,31,-15,16),(20,12,38,-8,9),(30,0,0,0,0)):
    for tag in ('L3','R3'): key(tag+'_Upper',f,(rear,0,0)); key(tag+'_Lower',f,(-rear*.75,0,0))
    for tag in ('L1','R1'): key(tag+'_Upper',f,(fore,0,0)); key(tag+'_Lower',f,(-fore*.68,0,0)); key(tag+'_Foot',f,(fore*.35,0,0))
    key('Brow',f,(brow,0,0)); key('Body',f,(body,0,0)); key('Head',f,(-body*.45,0,0))

action('Hit')
for f,r in ((1,0),(5,9),(10,-4),(16,0)): key('Body',f,(0,0,r)); key('Head',f,(0,0,r*.55))
action('Stagger')
for f,r,p in ((1,0,0),(8,22,-10),(16,-15,13),(23,7,-6),(30,0,0)):
    key('Body',f,(p,0,r)); key('Abdomen',f,(-p*.5,0,-r*.45)); key('Head',f,(p*.4,0,r*.55))
    for tag in LEGS: key(tag+'_Upper',f,(abs(r)*.42,0,0))

# Lithic death: legs progressively fold and the broad shell tips onto one armored flank.
action('Death')
for f,roll,drop in ((1,0,0),(16,16,-.03),(32,48,-.10),(45,76,-.18),(56,86,-.22)):
    key('Body',f,(8 if roll else 0,0,roll),loc=(0,0,drop)); key('Abdomen',f,(5 if roll else 0,0,roll*.72)); key('Head',f,(12 if roll else 0,0,-roll*.15)); key('Brow',f,(18 if roll else 0,0,-roll*.10))
    for tag in LEGS: key(tag+'_Upper',f,(min(42,roll*.44),0,0)); key(tag+'_Lower',f,(-min(48,roll*.50),0,0)); key(tag+'_Foot',f,(min(22,roll*.22),0,0))

# Structural contract gates.
def bone_has(a,b): return any(('pose.bones["%s"]'%b) in fc.data_path for fc in a.fcurves)
missing=[n for n in ACTIONS if bpy.data.actions.get('BC_'+n) is None]
if missing: raise RuntimeError(f'Missing Basalt Crawler actions: {missing}')
sc=bpy.data.actions['BC_Scuttle']; absent=[f'{t}_{s}' for t in LEGS for s in SEGS if not bone_has(sc,f'{t}_{s}')]
if absent: raise RuntimeError(f'Scuttle missing six-leg deformation stages: {absent}')
for n in ('Guard','Ram'):
    if not bone_has(bpy.data.actions['BC_'+n],'Brow'): raise RuntimeError(f'{n} does not articulate Brow guard surface')
for a in [bpy.data.actions['BC_'+n] for n in ACTIONS]:
    if any('pose.bones["Root"]' in fc.data_path and 'location' in fc.data_path for fc in a.fcurves): raise RuntimeError(f'{a.name} illegally animates Root.location')
arm['action_contract']=','.join(ACTIONS)
arm['animation_fidelity']='alternating-tripod low scuttle; heavy mirrored pivots; whole-body lateral/frontal strikes; physical brow shutter guard; braced in-place ram; lithic flank collapse'
arm['root_motion_policy']='Root translation reserved for Valheim runtime; all production actions are in-place'
bpy.ops.wm.save_as_mainfile(filepath=str(BLEND)); print(f'Authored {len(ACTIONS)} Basalt Crawler production actions into {BLEND}')
