#!/usr/bin/env python3
"""Author in-place production actions for the Sulfurous Wastes Cinder Hound.

Requires assets/models/source/underworld-creature-cinder-hound.blend generated by
`author-underworld-cinder-hound.py`. Valheim owns world translation; this file only
authors deformation, gait, combat telegraphs and pack/heat-vent behavior.
"""
from pathlib import Path
from math import radians, sin, pi
import bpy

ROOT=Path(__file__).resolve().parents[1]
BLEND=ROOT/'assets/models/source/underworld-creature-cinder-hound.blend'
if not BLEND.exists(): raise RuntimeError(f'Missing source blend: {BLEND}')
bpy.ops.wm.open_mainfile(filepath=str(BLEND))
arm=bpy.data.objects.get('RIG_CinderHound_HOST_QUADRUPED')
if not arm or arm.type!='ARMATURE': raise RuntimeError('Missing Cinder Hound HOST-QUADRUPED rig')
bpy.context.view_layer.objects.active=arm; arm.select_set(True); bpy.context.view_layer.update()

ACTIONS={'Idle':48,'VentIdle':64,'Walk':32,'PackSprint':20,'TurnLeft':24,'TurnRight':24,'Bite':18,'Lunge':24,'PackCall':42,'Hit':16,'Stagger':28,'Death':54}
LEGS=('FL','FR','HL','HR'); SEGS=('Upper','Lower','Hock','Foot')

def reset():
    for p in arm.pose.bones:
        p.rotation_mode='XYZ'; p.rotation_euler=(0,0,0); p.location=(0,0,0); p.scale=(1,1,1)
def action(name,end):
    a=bpy.data.actions.get('CH_'+name) or bpy.data.actions.new('CH_'+name); a.use_fake_user=True
    if arm.animation_data is None: arm.animation_data_create()
    arm.animation_data.action=a
    reset(); arm['active_action_contract']=name
    return a
def key(bone,frame,rot=None,loc=None):
    p=arm.pose.bones[bone]
    if rot is not None: p.rotation_euler=tuple(radians(v) for v in rot); p.keyframe_insert('rotation_euler',frame=frame,group=bone)
    if loc is not None: p.location=loc; p.keyframe_insert('location',frame=frame,group=bone)
def cyc(name,end,amp,body=2,tail=8):
    action(name,end)
    for f in range(1,end+1,4):
        phase=2*pi*(f-1)/(end-1)
        # diagonal pairs oppose each other; digitigrade hock/foot provide visible compression and toe-off.
        for tag in LEGS:
            ph=phase+(pi if tag in ('FR','HL') else 0)
            s=sin(ph)
            key(tag+'_Upper',f,(amp*s,0,0)); key(tag+'_Lower',f,(-amp*.72*s,0,0)); key(tag+'_Hock',f,(amp*.92*s,0,0)); key(tag+'_Foot',f,(-amp*.30*s,0,0))
        key('Spine',f,(body*sin(phase*2),0,0)); key('Chest',f,(-body*.7*sin(phase*2),0,0))
        key('Tail_1',f,(0,0,tail*.35*sin(phase))); key('Tail_2',f,(0,0,tail*.68*sin(phase-.35))); key('Tail_3',f,(0,0,tail*sin(phase-.7)))
    reset()

# Quiet living motion; no locomotion translation.
action('Idle',48)
for f,v in ((1,0),(13,2),(25,0),(37,-2),(48,0)):
    key('Chest',f,(v,0,0)); key('Neck',f,(-v*.5,0,0)); key('Tail_3',f,(0,0,v*1.5))

# Heat dump: chest expands, head lowers, jaw/throat opens while rib-vent anatomy remains readable.
action('VentIdle',64)
for f,ch,jaw,head in ((1,0,0,0),(14,5,12,-5),(30,8,24,-9),(46,5,18,-6),(64,0,0,0)):
    key('Chest',f,(ch,0,0)); key('Spine',f,(-ch*.35,0,0)); key('Head',f,(head,0,0)); key('Jaw',f,(jaw,0,0)); key('Tail_1',f,(0,0,-ch*.35)); key('Tail_2',f,(0,0,ch*.55))

cyc('Walk',32,20,2.5,9)
cyc('PackSprint',20,38,5.5,18)

# Turns commit chest/head and use outside-leg reach; opposite actions are true mirrors.
for name,sgn in (('TurnLeft',1),('TurnRight',-1)):
    action(name,24)
    for f,w in ((1,0),(8,1),(16,1),(24,0)):
        key('Chest',f,(0,0,sgn*14*w)); key('Neck',f,(0,0,sgn*18*w)); key('Head',f,(0,0,sgn*12*w)); key('Tail_1',f,(0,0,-sgn*15*w)); key('Tail_2',f,(0,0,-sgn*20*w))
        outer='FR' if sgn>0 else 'FL'; key(outer+'_Upper',f,(sgn*24*w,0,0)); key(outer+'_Hock',f,(-sgn*18*w,0,0))

# Bite is jaw-led; neck/chest recoil prevents a floating-mouth attack.
action('Bite',18)
for f,j,n,c in ((1,0,0,0),(5,34,-10,-4),(9,-8,17,8),(13,5,7,3),(18,0,0,0)):
    key('Jaw',f,(j,0,0)); key('Head',f,(n*.45,0,0)); key('Neck',f,(n,0,0)); key('Chest',f,(c,0,0))

# In-place lunge deformation: rear compression -> extension -> forelimb brace -> recoil. Runtime supplies displacement.
action('Lunge',24)
for f,hip,chest,fore,jaw in ((1,0,0,0,0),(6,34,-12,-14,20),(11,-28,18,24,-5),(16,16,8,32,3),(24,0,0,0,0)):
    for tag in ('HL','HR'): key(tag+'_Upper',f,(hip,0,0)); key(tag+'_Hock',f,(-hip*.75,0,0))
    for tag in ('FL','FR'): key(tag+'_Upper',f,(fore,0,0)); key(tag+'_Hock',f,(-fore*.65,0,0))
    key('Chest',f,(chest,0,0)); key('Neck',f,(-chest*.6,0,0)); key('Jaw',f,(jaw,0,0)); key('Tail_2',f,(0,0,-chest*.55))

# Pack call presents throat/vent anatomy without inventing gameplay signaling logic.
action('PackCall',42)
for f,neck,jaw,chest in ((1,0,0,0),(10,-18,16,5),(20,-30,27,10),(32,-20,20,7),(42,0,0,0)):
    key('Neck',f,(neck,0,0)); key('Head',f,(neck*.35,0,0)); key('Jaw',f,(jaw,0,0)); key('Chest',f,(chest,0,0)); key('Tail_1',f,(0,0,8 if f not in (1,42) else 0))

action('Hit',16)
for f,r in ((1,0),(5,12),(10,-5),(16,0)): key('Chest',f,(0,0,r)); key('Head',f,(0,0,r*.7))
action('Stagger',28)
for f,r,p in ((1,0,0),(7,25,-12),(15,-16,16),(22,8,-7),(28,0,0)):
    key('Chest',f,(p,0,r)); key('Spine',f,(-p*.6,0,-r*.5)); key('Head',f,(p*.5,0,r*.6))
    for tag in LEGS: key(tag+'_Upper',f,(abs(r)*.35,0,0))
action('Death',54)
for f,roll,drop in ((1,0,0),(16,18,-.05),(32,58,-.18),(44,82,-.27),(54,88,-.31)):
    key('Pelvis',f,(0,0,roll),loc=(0,0,drop)); key('Spine',f,(8 if roll else 0,0,roll*.55)); key('Chest',f,(14 if roll else 0,0,roll*.72)); key('Neck',f,(20 if roll else 0,0,-roll*.18)); key('Head',f,(28 if roll else 0,0,-roll*.12)); key('Jaw',f,(18 if roll else 0,0))
    for tag in LEGS: key(tag+'_Upper',f,(min(46,roll*.48),0,0)); key(tag+'_Hock',f,(-min(55,roll*.58),0,0))

# Contract gates: all actions, digitigrade participation, sprint distinctness, no Root translation.
def paths(a): return {(fc.data_path,fc.array_index) for fc in a.fcurves}
def bone_has(a,b): return any(('pose.bones["%s"]'%b) in fc.data_path for fc in a.fcurves)
missing=[n for n in ACTIONS if bpy.data.actions.get('CH_'+n) is None]
if missing: raise RuntimeError(f'Missing actions: {missing}')
for n in ('Walk','PackSprint'):
    a=bpy.data.actions['CH_'+n]
    absent=[f'{t}_{s}' for t in LEGS for s in SEGS if not bone_has(a,f'{t}_{s}')]
    if absent: raise RuntimeError(f'{n} missing digitigrade participation: {absent}')
for a in [bpy.data.actions['CH_'+n] for n in ACTIONS]:
    if bone_has(a,'Root') and any('location' in fc.data_path and 'Root' in fc.data_path for fc in a.fcurves): raise RuntimeError(f'{a.name} illegally animates Root.location')
arm['action_contract']='Idle,VentIdle,Walk,PackSprint,TurnLeft,TurnRight,Bite,Lunge,PackCall,Hit,Stagger,Death'
arm['animation_fidelity']='diagonal quadruped gait; compressed digitigrade pack sprint; segmented tail counterbalance; physical heat-vent idle; jaw-led bite; full-body in-place lunge; throat-presenting pack call'
arm['root_motion_policy']='Root translation reserved for Valheim runtime; all production actions are in-place'
bpy.ops.wm.save_as_mainfile(filepath=str(BLEND)); print(f'Authored {len(ACTIONS)} Cinder Hound production actions into {BLEND}')
