using System;
using Jotunn.Managers;
using UnityEngine;

namespace Magenheim.Runtime;

internal sealed class DarkThroneEncounterRuntime : MonoBehaviour
{
    private const string DefeatedKey="magenheim.darkthrone.defeated",EngagedKey="magenheim.darkthrone.engaged",RewardedKey="magenheim.darkthrone.rewarded",KingIdentityKey="magenheim.darkthrone.king.id",KingEncounterKey="magenheim.darkthrone.king.encounter",EncounterIdentityKey="magenheim.darkthrone.id";
    private const float DisengageGraceSeconds=12f; private ZNetView _view; private Transform _kingAnchor; private float _noParticipantsSince=-1f;
    internal bool HasBeenDefeated=>_view!=null&&_view.IsValid()&&_view.GetZDO().GetBool(DefeatedKey,false);
    internal bool IsKingActive{get{var king=FindEncounterKing();return king!=null&&!king.IsDead();}}
    private void Awake()=>_view=GetComponent<ZNetView>();
    private void Start(){_kingAnchor=transform.parent!=null?transform.parent.Find(DarkThroneVisuals.KingAnchorName):null;if(_kingAnchor==null){Debug.LogError("Dark Throne encounter has no Nowhere King anchor and will remain inert.");enabled=false;}}
    private void Update(){if(!HasAuthority())return;var zdo=_view.GetZDO();if(zdo.GetBool(DefeatedKey,false)){SuspendEcology(false);TryReleaseRewards(zdo);return;}var king=FindEncounterKing();if(king!=null&&king.IsDead()){var deadView=king.GetComponent<ZNetView>();if(deadView!=null&&deadView.IsValid())MarkDefeated(deadView.GetZDO());return;}if(king==null){king=SpawnKing();if(king==null)return;}BindRuntime(king);var participants=CountLivingParticipants();var engaged=zdo.GetBool(EngagedKey,false);if(participants>0){_noParticipantsSince=-1f;if(!engaged){zdo.Set(EngagedKey,true);SuspendEcology(true);}return;}if(!engaged)return;if(_noParticipantsSince<0f)_noParticipantsSince=Time.time;if(Time.time-_noParticipantsSince<DisengageGraceSeconds)return;ResetEncounter(king);}
    internal void MarkDefeated(ZDO kingZdo){if(!HasAuthority()||kingZdo==null)return;var encounterId=EnsureEncounterIdentity();if(!string.Equals(kingZdo.GetString(KingEncounterKey,string.Empty),encounterId,StringComparison.Ordinal))return;var zdo=_view.GetZDO();if(zdo.GetBool(DefeatedKey,false))return;zdo.Set(DefeatedKey,true);zdo.Set(EngagedKey,false);zdo.Set(KingIdentityKey,string.Empty);zdo.Set(RewardedKey,false);_noParticipantsSince=-1f;SuspendEcology(false);TryReleaseRewards(zdo);}
    internal bool TryResummonKing()
    {
        if(!HasAuthority())return false;var zdo=_view.GetZDO();if(!zdo.GetBool(DefeatedKey,false)||IsKingActive)return false;
        zdo.Set(DefeatedKey,false);zdo.Set(EngagedKey,false);zdo.Set(KingIdentityKey,string.Empty);_noParticipantsSince=-1f;
        var king=SpawnKing();if(king!=null){SuspendEcology(false);return true;}
        zdo.Set(DefeatedKey,true);return false;
    }
    private bool HasAuthority()=>_view!=null&&_view.IsValid()&&_view.IsOwner()&&ZNet.instance!=null;
    private int CountLivingParticipants(){var center=transform.position,count=0;foreach(var player in Player.GetAllPlayers()){if(player==null||player.IsDead())continue;var d=player.transform.position-center;if(Mathf.Abs(d.x)<=34f&&Mathf.Abs(d.z)<=38f)count++;}return count;}
    private Character FindEncounterKing(){if(_view==null||!_view.IsValid())return null;var encounterId=EnsureEncounterIdentity();foreach(var character in Character.GetAllCharacters()){if(character==null)continue;var nview=character.GetComponent<ZNetView>();if(nview!=null&&nview.IsValid()&&string.Equals(nview.GetZDO().GetString(KingEncounterKey,string.Empty),encounterId,StringComparison.Ordinal))return character;}return null;}
    private Character SpawnKing(){var prefab=PrefabManager.Instance.GetPrefab(NowhereKingRegistrar.PrefabName);if(prefab==null||_kingAnchor==null)return null;var instance=Instantiate(prefab,_kingAnchor.position,_kingAnchor.rotation);var character=instance.GetComponent<Character>();var nview=instance.GetComponent<ZNetView>();if(character==null||nview==null||!nview.IsValid()){Destroy(instance);return null;}nview.GetZDO().Set(KingEncounterKey,EnsureEncounterIdentity());_view.GetZDO().Set(KingIdentityKey,nview.GetZDO().m_uid.ToString());BindRuntime(character);return character;}
    private void BindRuntime(Character king){var leash=king.GetComponent<NowhereKingArenaLeash>();if(leash!=null)leash.Configure(transform.position);var link=king.GetComponent<NowhereKingEncounterLink>()??king.gameObject.AddComponent<NowhereKingEncounterLink>();link.Bind(this);var p1=king.GetComponent<NowhereKingPhaseOneCombat>()??king.gameObject.AddComponent<NowhereKingPhaseOneCombat>();p1.Configure(transform.position);var p2=king.GetComponent<NowhereKingPhaseTwoCombat>()??king.gameObject.AddComponent<NowhereKingPhaseTwoCombat>();p2.Configure(transform.position);var p3=king.GetComponent<NowhereKingPhaseThreeCombat>()??king.gameObject.AddComponent<NowhereKingPhaseThreeCombat>();p3.Configure(transform.position);if(king.GetComponent<NowhereKingPhaseTransition>()==null)king.gameObject.AddComponent<NowhereKingPhaseTransition>();if(king.GetComponent<NowhereKingAdaptiveResistance>()==null)king.gameObject.AddComponent<NowhereKingAdaptiveResistance>();if(king.GetComponent<NowhereKingRoyalStagger>()==null)king.gameObject.AddComponent<NowhereKingRoyalStagger>();}
    private string EnsureEncounterIdentity(){var zdo=_view.GetZDO();var id=zdo.GetString(EncounterIdentityKey,string.Empty);if(!string.IsNullOrWhiteSpace(id))return id;var p=transform.position;id=string.Concat("darkthrone:",Mathf.RoundToInt(p.x),":",Mathf.RoundToInt(p.y),":",Mathf.RoundToInt(p.z));zdo.Set(EncounterIdentityKey,id);return id;}
    private void ResetEncounter(Character king){var zdo=_view.GetZDO();zdo.Set(EngagedKey,false);_noParticipantsSince=-1f;SuspendEcology(false);if(king==null)return;var phaseThree=king.GetComponent<NowhereKingPhaseThreeCombat>();if(phaseThree!=null)phaseThree.ResetState();king.Heal(king.GetMaxHealth(),true);king.SetPos(_kingAnchor.position);var resistance=king.GetComponent<NowhereKingAdaptiveResistance>();if(resistance!=null)resistance.ResetAdaptation();var stagger=king.GetComponent<NowhereKingRoyalStagger>();if(stagger!=null)stagger.ResetState();var body=king.GetComponent<Rigidbody>();if(body!=null){body.velocity=Vector3.zero;body.angularVelocity=Vector3.zero;}}
    private void TryReleaseRewards(ZDO zdo){if(zdo.GetBool(RewardedKey,false))return;var mantle=PrefabManager.Instance.GetPrefab(NowhereKingRewardRegistrar.NullMantlePrefabName);var trophy=PrefabManager.Instance.GetPrefab(NowhereKingRewardRegistrar.TrophyPrefabName);if(mantle==null||trophy==null)return;zdo.Set(RewardedKey,true);try{var origin=_kingAnchor!=null?_kingAnchor.position:transform.position;Instantiate(mantle,origin+new Vector3(-1.2f,1.1f,0f),Quaternion.identity);Instantiate(trophy,origin+new Vector3(1.2f,1.1f,0f),Quaternion.identity);}catch(Exception exception){Debug.LogError($"Dark Throne reward release failed after durable reservation: {exception}");}}
    private void SuspendEcology(bool suspended){var root=transform.parent!=null?transform.parent:transform;foreach(var spawner in root.GetComponentsInChildren<DarkThroneCrystalSpawner>(true))spawner.SetEncounterSuspended(suspended);}
}
