using System;
using System.Collections.Generic;
using System.Linq;
using Magenheim.Core;
using UnityEngine;

namespace Magenheim.Runtime;

internal static class DeepFractureCreatureVisuals
{
    private static readonly Dictionary<int, Mesh> PrismMeshes = new();
    internal static void ApplyAnnoyanceWisp(GameObject prefab, ElementalAlignment alignment) { var c = Begin(prefab,"annoyance-wisp",alignment); Prism(c.Root,"motion-core",Vector3.zero,.22f,.58f,7,c.Core); Prism(c.Root,"crystal-shell",Vector3.zero,.38f,.82f,7,c.Shell); for(var i=0;i<5;i++){var a=Mathf.PI*2f*i/5f+.28f;Prism(c.Root,"orbit-shard-"+i,new Vector3(Mathf.Cos(a)*.48f,-.03f+((i&1)==0?.08f:-.05f),Mathf.Sin(a)*.48f),.075f,.30f,5,c.Shard,new Vector3(22f,-a*Mathf.Rad2Deg,34f));} Finish(prefab,c,3.2f,.85f); }
    internal static void ApplyGeodeCrawler(GameObject prefab, ElementalAlignment alignment) { var c=Begin(prefab,"geode-crawler",alignment);c.Root.transform.localPosition=new Vector3(0f,.08f,0f);Prism(c.Root,"stone-abdomen",new Vector3(0f,.12f,-.18f),.43f,.72f,8,c.Shell,new Vector3(90f,0f,0f));Prism(c.Root,"stone-thorax",new Vector3(0f,.12f,.34f),.32f,.48f,7,c.Shell,new Vector3(90f,0f,0f));Prism(c.Root,"carapace-core",new Vector3(0f,.39f,-.12f),.23f,.38f,6,c.Core,new Vector3(8f,0f,0f));for(var i=0;i<3;i++){var z=-.27f+i*.30f;Prism(c.Root,"left-leg-"+i,new Vector3(-.43f,-.04f,z),.075f,.58f,5,c.Shard,new Vector3(0f,0f,62f));Prism(c.Root,"right-leg-"+i,new Vector3(.43f,-.04f,z),.075f,.58f,5,c.Shard,new Vector3(0f,0f,-62f));}Prism(c.Root,"left-mandible",new Vector3(-.17f,.06f,.63f),.065f,.30f,5,c.Core,new Vector3(70f,0f,18f));Prism(c.Root,"right-mandible",new Vector3(.17f,.06f,.63f),.065f,.30f,5,c.Core,new Vector3(70f,0f,-18f));Finish(prefab,c,2.4f,.55f); }
    internal static void ApplyShardling(GameObject prefab, ElementalAlignment alignment) { var c=Begin(prefab,"shardling",alignment);c.Root.transform.localPosition=new Vector3(0f,.76f,0f);Prism(c.Root,"locomotion-core",new Vector3(0f,.12f,0f),.19f,.48f,6,c.Core);Prism(c.Root,"torso-shard",new Vector3(0f,.34f,0f),.29f,.82f,5,c.Shell,new Vector3(-5f,0f,0f));Prism(c.Root,"head-shard",new Vector3(0f,.87f,.02f),.21f,.47f,5,c.Shard);Prism(c.Root,"left-arm-blade",new Vector3(-.39f,.33f,.04f),.075f,.76f,5,c.Shard,new Vector3(0f,0f,-31f));Prism(c.Root,"right-arm-blade",new Vector3(.39f,.33f,.04f),.075f,.76f,5,c.Shard,new Vector3(0f,0f,31f));Prism(c.Root,"left-runner",new Vector3(-.18f,-.37f,.01f),.085f,.86f,5,c.Shell,new Vector3(0f,0f,-7f));Prism(c.Root,"right-runner",new Vector3(.18f,-.37f,.01f),.085f,.86f,5,c.Shell,new Vector3(0f,0f,7f));Finish(prefab,c,2.1f,.42f); }
    internal static void ApplyCrystalParasite(GameObject prefab, ElementalAlignment alignment)
    {
        var c=Begin(prefab,"crystal-parasite",alignment); c.Root.transform.localPosition=new Vector3(0f,.18f,0f);
        Prism(c.Root,"regrowth-core",new Vector3(0f,.24f,-.08f),.25f,.54f,7,c.Core,new Vector3(88f,0f,0f));
        for(var i=0;i<5;i++){var z=-.52f+i*.25f;var r=.29f-i*.018f;Prism(c.Root,"segmented-body-"+i,new Vector3(0f,.05f,z),r,.32f,7,c.Shell,new Vector3(90f,0f,0f));}
        for(var i=0;i<4;i++){var z=-.38f+i*.27f;Prism(c.Root,"left-hook-"+i,new Vector3(-.30f,-.08f,z),.055f,.42f,4,c.Shard,new Vector3(0f,0f,66f));Prism(c.Root,"right-hook-"+i,new Vector3(.30f,-.08f,z),.055f,.42f,4,c.Shard,new Vector3(0f,0f,-66f));}
        Prism(c.Root,"feeding-spike-left",new Vector3(-.11f,.02f,.58f),.06f,.39f,5,c.Core,new Vector3(78f,0f,15f));Prism(c.Root,"feeding-spike-right",new Vector3(.11f,.02f,.58f),.06f,.39f,5,c.Core,new Vector3(78f,0f,-15f));
        Prism(c.Root,"dorsal-growth-0",new Vector3(0f,.39f,-.35f),.08f,.43f,5,c.Shard,new Vector3(-12f,0f,0f));Prism(c.Root,"dorsal-growth-1",new Vector3(.08f,.38f,.10f),.07f,.36f,5,c.Shard,new Vector3(9f,0f,11f));
        Finish(prefab,c,2.6f,.62f);
    }

    private sealed record VisualContext(GameObject Root,Renderer[] Original,Color Tint,Material Shell,Material Core,Material Shard);
    private static VisualContext Begin(GameObject prefab,string family,ElementalAlignment alignment){if(prefab is null)throw new ArgumentNullException(nameof(prefab));var original=prefab.GetComponentsInChildren<Renderer>(true);var source=original.Select(r=>r.sharedMaterial).FirstOrDefault(m=>m)??throw new InvalidOperationException($"Creature host '{prefab.name}' exposes no material source.");var root=new GameObject("magenheim.fracture.creature."+family+".visual"){layer=prefab.layer};root.transform.SetParent(prefab.transform,false);var tint=ElementVisualPalette.Tint(alignment);return new VisualContext(root,original,tint,Material(source,family+".shell",Color.Lerp(tint,new Color(.28f,.25f,.22f),.62f),.18f,.58f,.18f),Material(source,family+".core",Color.Lerp(tint,Color.white,.68f),.02f,.96f,1.35f),Material(source,family+".shard",tint,.05f,.78f,.82f));}
    private static void Finish(GameObject prefab,VisualContext c,float range,float intensity){var l=c.Root.AddComponent<Light>();l.color=c.Tint;l.range=range;l.intensity=intensity;foreach(var r in c.Original)if(!r.transform.IsChildOf(c.Root.transform))r.enabled=false;foreach(var lod in prefab.GetComponentsInChildren<LODGroup>(true))lod.enabled=false;}
    private static Material Material(Material source,string suffix,Color color,float metallic,float gloss,float emission){var m=new Material(source){name="magenheim.fracture.creature."+suffix};m.mainTexture=Texture2D.whiteTexture;m.mainTextureScale=Vector2.one;m.mainTextureOffset=Vector2.zero;if(m.HasProperty("_Color"))m.SetColor("_Color",color);if(m.HasProperty("_Metallic"))m.SetFloat("_Metallic",metallic);if(m.HasProperty("_Glossiness"))m.SetFloat("_Glossiness",gloss);if(m.HasProperty("_BumpMap"))m.SetTexture("_BumpMap",null);m.DisableKeyword("_NORMALMAP");if(m.HasProperty("_EmissionColor")){m.SetColor("_EmissionColor",color*emission);m.EnableKeyword("_EMISSION");}m.SetOverrideTag("RenderType","Opaque");if(m.HasProperty("_ZWrite"))m.SetFloat("_ZWrite",1f);m.renderQueue=2000;return m;}
    private static void Prism(GameObject root,string name,Vector3 position,float radius,float height,int sides,Material material,Vector3? rotation=null){if(!PrismMeshes.TryGetValue(sides,out var mesh)){mesh=CreatePrismMesh(sides);PrismMeshes.Add(sides,mesh);}var part=new GameObject(name){layer=root.layer};part.transform.SetParent(root.transform,false);part.transform.localPosition=position;part.transform.localRotation=Quaternion.Euler(rotation??Vector3.zero);part.transform.localScale=new Vector3(radius*2f,height,radius*2f);part.AddComponent<MeshFilter>().sharedMesh=mesh;part.AddComponent<MeshRenderer>().sharedMaterial=material;}
    private static Mesh CreatePrismMesh(int sides){var v=new List<Vector3>(sides*2+2);var t=new List<int>(sides*12);for(var i=0;i<sides;i++){var a=2f*Mathf.PI*i/sides;v.Add(new Vector3(.36f*Mathf.Cos(a),-.45f,.36f*Mathf.Sin(a)));}for(var i=0;i<sides;i++){var a=2f*Mathf.PI*i/sides;v.Add(new Vector3(.5f*Mathf.Cos(a),.20f,.5f*Mathf.Sin(a)));}var top=v.Count;v.Add(new Vector3(0f,.68f,0f));var bottom=v.Count;v.Add(new Vector3(0f,-.50f,0f));for(var i=0;i<sides;i++){var n=(i+1)%sides;t.AddRange(new[]{bottom,n,i,i,n,sides+i,n,sides+n,sides+i,sides+i,sides+n,top});}var mesh=new Mesh{name="magenheim.fracture.creature.prism."+sides,vertices=v.ToArray(),triangles=t.ToArray()};mesh.RecalculateNormals();mesh.RecalculateBounds();return mesh;}
}
