using System;using System.Collections.Generic;using System.Linq;using Magenheim.Core;using UnityEngine;namespace Magenheim.Runtime;internal static class DeepFractureDeepColossusVisual{
 private static readonly Dictionary<int,Mesh> Meshes=new Dictionary<int,Mesh>();
 internal static void Apply(GameObject prefab,ElementalAlignment alignment){var original=prefab.GetComponentsInChildren<Renderer>(true);var source=original.Select(r=>r.sharedMaterial).FirstOrDefault(m=>m)??throw new InvalidOperationException("Deep Colossus host has no material source.");var root=new GameObject("magenheim.fracture.creature.deep-colossus.visual"){layer=prefab.layer};root.transform.SetParent(prefab.transform,false);root.transform.localPosition=new Vector3(0,2.65f,0);var tint=ElementVisualPalette.Tint(alignment);var stone=Material(source,Color.Lerp(tint,new Color(.16f,.15f,.14f),.72f),.18f);var crystal=Material(source,tint,1.15f);var core=Material(source,Color.Lerp(tint,Color.white,.72f),1.75f);
 P(root,"world-core",new Vector3(0,.85f,-.4f),.58f,1.25f,8,core);P(root,"citadel-torso",new Vector3(0,.72f,0),1.35f,2.5f,8,stone);P(root,"crown",new Vector3(0,2.35f,.02f),.78f,1.0f,7,stone);P(root,"face-core",new Vector3(0,2.35f,.72f),.3f,.7f,6,core,new Vector3(84,0,0));
 for(int side=-1;side<=1;side+=2){P(root,"armor-core-"+side,new Vector3(1.32f*side,1.08f,-.08f),.36f,.8f,7,core,new Vector3(0,0,28*side));P(root,"shoulder-"+side,new Vector3(1.38f*side,1.18f,0),.78f,1.15f,8,stone,new Vector3(0,0,24*side));P(root,"arm-"+side,new Vector3(1.7f*side,-.15f,.04f),.42f,2.45f,8,stone,new Vector3(0,0,5*side));P(root,"fist-"+side,new Vector3(1.78f*side,-1.45f,.18f),.62f,.9f,7,crystal);P(root,"leg-"+side,new Vector3(.62f*side,-1.65f,0),.58f,2.55f,8,stone);P(root,"knee-"+side,new Vector3(.62f*side,-1.05f,.55f),.28f,.65f,6,crystal,new Vector3(72,0,0));}
 P(root,"regeneration-core",new Vector3(0,1.18f,.78f),.42f,.85f,8,core,new Vector3(82,0,0));P(root,"resistance-core",new Vector3(0,.22f,-.92f),.38f,.78f,8,core,new Vector3(82,0,0));P(root,"death-anchor",new Vector3(0,-.42f,-1.02f),.34f,.72f,7,core,new Vector3(82,0,0));
 for(int i=0;i<9;i++){float x=(i-4)*.27f;P(root,"crown-spire-"+i,new Vector3(x,2.92f,-.12f+Mathf.Abs(i-4)*.04f),.10f+(4-Mathf.Abs(i-4))*.018f,.8f+(.4f-Mathf.Abs(i-4)*.06f),5,crystal,new Vector3(-8,0,(i-4)*6));}
 var light=root.AddComponent<Light>();light.color=tint;light.range=7.5f;light.intensity=1.35f;foreach(var r in original)if(!r.transform.IsChildOf(root.transform))r.enabled=false;foreach(var lod in prefab.GetComponentsInChildren<LODGroup>(true))lod.enabled=false;
 }
 private static Material Material(Material source,Color color,float emission){var m=new Material(source);m.mainTexture=Texture2D.whiteTexture;m.mainTextureOffset=Vector2.zero;m.mainTextureScale=Vector2.one;if(m.HasProperty("_Color"))m.SetColor("_Color",color);if(m.HasProperty("_BumpMap"))m.SetTexture("_BumpMap",null);if(m.HasProperty("_EmissionColor")){m.SetColor("_EmissionColor",color*emission);m.EnableKeyword("_EMISSION");}m.SetOverrideTag("RenderType","Opaque");if(m.HasProperty("_ZWrite"))m.SetFloat("_ZWrite",1);m.renderQueue=2000;return m;}
 private static void P(GameObject root,string name,Vector3 position,float radius,float height,int sides,Material material,Vector3? rotation=null){Mesh mesh;if(!Meshes.TryGetValue(sides,out mesh)){mesh=CreateMesh(sides);Meshes.Add(sides,mesh);}var part=new GameObject(name){layer=root.layer};part.transform.SetParent(root.transform,false);part.transform.localPosition=position;part.transform.localRotation=Quaternion.Euler(rotation??Vector3.zero);part.transform.localScale=new Vector3(radius*2,height,radius*2);part.AddComponent<MeshFilter>().sharedMesh=mesh;part.AddComponent<MeshRenderer>().sharedMaterial=material;}
 private static Mesh CreateMesh(int sides){var v=new List<Vector3>();var t=new List<int>();for(int i=0;i<sides;i++){float a=2*Mathf.PI*i/sides;v.Add(new Vector3(.36f*Mathf.Cos(a),-.45f,.36f*Mathf.Sin(a)));}for(int i=0;i<sides;i++){float a=2*Mathf.PI*i/sides;v.Add(new Vector3(.5f*Mathf.Cos(a),.2f,.5f*Mathf.Sin(a)));}int top=v.Count;v.Add(new Vector3(0,.68f,0));int bottom=v.Count;v.Add(new Vector3(0,-.5f,0));for(int i=0;i<sides;i++){int n=(i+1)%sides;t.AddRange(new[]{bottom,n,i,i,n,sides+i,n,sides+n,sides+i,sides+i,sides+n,top});}var m=new Mesh{vertices=v.ToArray(),triangles=t.ToArray()};m.RecalculateNormals();m.RecalculateBounds();return m;}}
