using System;
using Magenheim.Core;
using UnityEngine;
namespace Magenheim.Runtime;
internal static class DeepFractureEncounterAnchors
{
 private const string RootName="Magenheim_EncounterAnchors"; private const int AuthoredSlotsPerRole=16;
 internal static void BakePrefab(Transform district,string id){if(district is null)throw new ArgumentNullException(nameof(district));var root=EnsureRoot(district,id);if(!IsAuthoredDistrict(id))return;foreach(var role in new[]{"Control","Heavy","Ambush","Air","Flank","Line"}){var rr=FindOrCreate(root,role);for(var slot=0;slot<AuthoredSlotsPerRole;slot++){var name=$"Authored_{slot:00}";if(rr.Find(name)is not null)continue;var p=AuthoredPose(id,role,slot);var a=new GameObject(name).transform;a.SetParent(rr,false);a.localPosition=p.Position;a.localRotation=Quaternion.Euler(0f,p.YawDegrees,0f);}}}
 internal static Transform Resolve(Transform district,string id,CreatureChassis chassis,int groupIndex,int unitIndex,int groupSize){if(district is null)throw new ArgumentNullException(nameof(district));var root=EnsureRoot(district,id);var role=Role(chassis);var rr=FindOrCreate(root,role);if(IsAuthoredDistrict(id)){var slot=(groupIndex*7+unitIndex)%AuthoredSlotsPerRole;return rr.Find($"Authored_{slot:00}")??throw new InvalidOperationException($"Deep Fracture prefab '{id}' is missing authored {role} encounter anchor {slot:00}.");}var name=$"{role}_{groupIndex:00}_{unitIndex:00}";var existing=rr.Find(name);if(existing is not null)return existing;var p=ProceduralPose(id,chassis,groupIndex,unitIndex,groupSize);var a=new GameObject(name).transform;a.SetParent(rr,false);a.localPosition=p.Position;a.localRotation=Quaternion.Euler(0f,p.YawDegrees,0f);return a;}
 private static bool IsAuthoredDistrict(string id)=>id is "DF-01" or "DF-02" or "DF-03" or "DF-04" or "DF-05" or "DF-06" or "DF-07" or "DF-08" or "DF-09" or "DF-10" or "DF-11" or "DF-12" or "DF-13" or "DF-14" or "DF-15";
 private static SpawnPose AuthoredPose(string id,string role,int slot){var ring=slot%8;var layer=slot/8;var angle=ring*45f*Mathf.Deg2Rad;var r=(id switch{"DF-01"=>19f,"DF-02"=>25f,"DF-03"=>24f,"DF-04"=>27f,"DF-05"=>25f,"DF-06"=>25f,"DF-07"=>27f,"DF-08"=>23f,"DF-09"=>30f,"DF-10"=>29f,"DF-11"=>24f,"DF-12"=>25f,"DF-13"=>28f,"DF-14"=>27f,"DF-15"=>26f,_=>22f})+layer*7f;var center=id switch{"DF-01"=>new Vector3(0,0,10),"DF-04"=>new Vector3(0,0,3),_=>Vector3.zero};var pos=center+new Vector3(Mathf.Cos(angle)*r,.35f,Mathf.Sin(angle)*r);switch(role){case"Air":pos.y=4.2f+layer*1.4f;break;case"Heavy":pos=Vector3.Lerp(center+Vector3.up*.35f,pos,.42f);break;case"Control":pos=center+new Vector3(Mathf.Cos(angle)*(r+4),.6f,Mathf.Sin(angle)*(r+4));break;case"Ambush":pos=center+new Vector3(Mathf.Cos(angle)*(r+2),.05f,Mathf.Sin(angle)*(r+2));break;case"Flank":pos+=new Vector3(Mathf.Sin(angle)*4,0,-Mathf.Cos(angle)*4);break;}
 if(id=="DF-01")pos.z=Mathf.Clamp(pos.z,-18,30);if(id=="DF-02")pos.x+=pos.z>0?-5:5;if(id=="DF-03"&&role=="Heavy")pos*=.72f;if(id=="DF-04")pos.x=Mathf.Abs(pos.x)<12?(pos.x<0?-18:18):pos.x;if(id=="DF-05"&&role=="Ambush")pos.z=(slot&1)==0?23:-23;
 if(id=="DF-06"){if(role=="Heavy")pos=new Vector3((ring-3.5f)*2.2f,.35f,layer==0?3:-5);else if(role=="Ambush")pos=new Vector3((ring&1)==0?-24:24,.05f,(ring-3.5f)*6);}if(id=="DF-07"){pos.z+=(ring&1)==0?7:-7;if(role=="Air")pos.y=6+layer*1.5f;}if(id=="DF-08"){if(role=="Heavy")pos=new Vector3((ring-3.5f)*1.8f,.35f,9-layer*8);if(role=="Control")pos=new Vector3((ring&1)==0?-27:27,1.1f,(ring-3.5f)*5);}if(id is "DF-09" or "DF-10"){if(role=="Control"){pos.y=4.8f+layer*2.2f;pos.x*=.92f;pos.z*=.92f;}if(role=="Flank")pos=center+new Vector3((ring&1)==0?-21:21,.35f,(ring-3.5f)*7);}
 if(id=="DF-11"){if(role=="Heavy")pos=new Vector3((ring-3.5f)*2.5f,.35f,layer==0?10:-8);else if(role=="Line")pos=new Vector3((ring-3.5f)*6,.35f,(ring&1)==0?15:-15);}if(id=="DF-12"){if(role=="Heavy")pos=new Vector3((ring-3.5f)*2,.35f,layer==0?7:-7);else if(role=="Flank")pos=new Vector3((ring&1)==0?-23:23,.35f,(ring-3.5f)*6);}if(id=="DF-13"){if(role=="Ambush")pos=new Vector3((ring&1)==0?-29:29,.05f,(ring-3.5f)*6.5f);else if(role=="Air")pos.y=5.5f+layer*1.5f;}if(id=="DF-14"){if(role=="Ambush")pos=new Vector3((ring-3.5f)*6.5f,.05f,(ring&1)==0?-26:26);else if(role=="Control")pos=new Vector3((ring&1)==0?-25:25,1.4f,(ring-3.5f)*5);}if(id=="DF-15"){if(role=="Control")pos=new Vector3(Mathf.Cos(angle)*29,3.5f+layer*2,Mathf.Sin(angle)*29);else if(role=="Line")pos=new Vector3((ring-3.5f)*5.5f,.35f,layer==0?13:-13);else if(role=="Flank")pos=new Vector3((ring&1)==0?-24:24,.35f,(ring-3.5f)*6);}return new SpawnPose(pos,Face(center,pos));}
 private static Transform EnsureRoot(Transform d,string id){var e=d.Find(RootName);if(e is not null)return e;_=Profile(id);var r=new GameObject(RootName).transform;r.SetParent(d,false);return r;}private static Transform FindOrCreate(Transform p,string n){var e=p.Find(n);if(e is not null)return e;var c=new GameObject(n).transform;c.SetParent(p,false);return c;}private static string Role(CreatureChassis c)=>c switch{CreatureChassis.FacetSentry or CreatureChassis.ObeliskWarden=>"Control",CreatureChassis.StoneSentinel or CreatureChassis.StoneGuardian or CreatureChassis.CrystalGolem or CreatureChassis.DeepColossus=>"Heavy",CreatureChassis.Burrower or CreatureChassis.CrystalParasite=>"Ambush",CreatureChassis.AnnoyanceWisp=>"Air",CreatureChassis.CrystalHound or CreatureChassis.Shardling=>"Flank",_=>"Line"};
 private static SpawnPose ProceduralPose(string id,CreatureChassis c,int g,int u,int n){var p=Profile(id);var lane=u-(n-1)*.5f;var flank=lane*p.Spacing;var depth=((u&1)==0?1:-1)*p.DepthSpread;var pos=p.Center+new Vector3(flank,.35f,depth);var yaw=Face(Vector3.zero,pos);switch(c){case CreatureChassis.FacetSentry:case CreatureChassis.ObeliskWarden:pos=p.Center+Radial(g,u,p.EdgeRadius);yaw=Face(Vector3.zero,pos);break;case CreatureChassis.StoneSentinel:case CreatureChassis.StoneGuardian:case CreatureChassis.CrystalGolem:case CreatureChassis.DeepColossus:pos=p.Center+new Vector3(flank*.45f,.35f,depth*.25f);yaw=Face(Vector3.zero,pos);break;case CreatureChassis.Burrower:case CreatureChassis.CrystalParasite:pos=p.Center+Radial(g+3,u,p.EdgeRadius*.82f);yaw=Face(Vector3.zero,pos);break;case CreatureChassis.AnnoyanceWisp:pos.y=2.8f+(u%3)*.7f;break;case CreatureChassis.CrystalHound:case CreatureChassis.Shardling:pos.x+=((u&1)==0?-1:1)*4;yaw=Face(Vector3.zero,pos);break;}return new SpawnPose(pos,yaw);}private static float Face(Vector3 c,Vector3 p)=>Mathf.Atan2(c.x-p.x,c.z-p.z)*Mathf.Rad2Deg;private static Vector3 Radial(int g,int u,float r){var a=(g*137.5f+u*61)*Mathf.Deg2Rad;return new Vector3(Mathf.Cos(a)*r,.35f,Mathf.Sin(a)*r);}
 private static DistrictProfile Profile(string id)=>id switch{"DF-01"=>new(new Vector3(0,0,12),5.5f,6,24),"DF-02"=>new(Vector3.zero,5,10,27),"DF-03"=>new(Vector3.zero,6,7,29),"DF-04"=>new(new Vector3(0,0,3),5,14,25),"DF-05"=>new(Vector3.zero,6,9,29),"DF-06"=>new(Vector3.zero,7,5,25),"DF-07"=>new(Vector3.zero,5,13,27),"DF-08"=>new(Vector3.zero,7,5,24),"DF-09"=>new(Vector3.zero,5,12,31),"DF-10"=>new(Vector3.zero,5,11,30),"DF-11"=>new(Vector3.zero,6,7,25),"DF-12"=>new(Vector3.zero,7,5,25),"DF-13"=>new(Vector3.zero,5,10,29),"DF-14"=>new(Vector3.zero,5,9,28),"DF-15"=>new(Vector3.zero,6,8,27),"DF-16"=>new(Vector3.zero,6,7,26),"DF-17"=>new(Vector3.zero,5,12,30),"DF-18"=>new(Vector3.zero,5,10,29),"DF-19"=>new(Vector3.zero,6,8,27),"DF-20"=>new(Vector3.zero,9,4,30),_=>throw new InvalidOperationException($"No encounter anchor profile exists for Deep Fracture district '{id}'.")};private readonly struct SpawnPose{internal SpawnPose(Vector3 p,float y){Position=p;YawDegrees=y;}internal Vector3 Position{get;}internal float YawDegrees{get;}}private readonly struct DistrictProfile{internal DistrictProfile(Vector3 c,float s,float d,float e){Center=c;Spacing=s;DepthSpread=d;EdgeRadius=e;}internal Vector3 Center{get;}internal float Spacing{get;}internal float DepthSpread{get;}internal float EdgeRadius{get;}}
}