using Magenheim.Core;
using UnityEngine;
namespace Magenheim.Runtime;
/// <summary>Attack-synchronized presentation for the heavy Deep Fracture chassis. Damage remains owned by the inherited Valheim attack items.</summary>
internal sealed class DeepFractureHeavyImpactRuntime:MonoBehaviour
{
    internal enum Profile{CrystalGolem,DeepColossus}
    internal Profile ImpactProfile;
    internal ElementalAlignment Alignment;
    private Humanoid? _humanoid;
    private bool _wasAttacking,_armed;
    private float _impactAt;
    private void Awake()=>_humanoid=GetComponent<Humanoid>();
    private void Update(){if(_humanoid==null)return;var attacking=_humanoid.InAttack();if(attacking&&!_wasAttacking){_armed=true;_impactAt=Time.time+(ImpactProfile==Profile.DeepColossus ? .62f : .46f);}if(_armed&&Time.time>=_impactAt){_armed=false;EmitImpact();}_wasAttacking=attacking;}
    private void EmitImpact(){var origin=transform.position+transform.forward*(ImpactProfile==Profile.DeepColossus?2.2f:1.45f)+Vector3.up*.08f;var rings=ImpactProfile==Profile.DeepColossus?3:2;for(var i=0;i<rings;i++){var ring=GameObject.CreatePrimitive(PrimitiveType.Cylinder);ring.name="Magenheim_HeavyImpactWave";ring.transform.position=origin+Vector3.up*(.015f*i);ring.transform.localScale=new Vector3(.45f+i*.55f,.018f,.45f+i*.55f);var c=ring.GetComponent<Collider>();if(c)Destroy(c);var r=ring.GetComponent<Renderer>();Material? material=null;if(r){material=new Material(Shader.Find("Standard"));material.color=ImpactProfile==Profile.DeepColossus?new Color(.42f,.18f,.62f,.62f):new Color(.34f,.62f,.78f,.56f);material.SetFloat("_Metallic",.15f);material.SetFloat("_Glossiness",.35f);r.material=material;}var fx=ring.AddComponent<HeavyImpactWave>();fx.Configure(ImpactProfile==Profile.DeepColossus?5.8f:3.8f,.48f+i*.08f,material);}var shards=ImpactProfile==Profile.DeepColossus?12:7;for(var i=0;i<shards;i++){var shard=GameObject.CreatePrimitive(PrimitiveType.Cube);shard.name="Magenheim_HeavyImpactShard";shard.transform.position=origin+Random.insideUnitSphere*.35f;shard.transform.localScale=new Vector3(.08f,.16f,.08f)*(ImpactProfile==Profile.DeepColossus?1.35f:1f);var c=shard.GetComponent<Collider>();if(c)Destroy(c);var body=shard.AddComponent<Rigidbody>();body.mass=.05f;body.velocity=(Quaternion.Euler(0,360f*i/shards,0)*Vector3.forward)*(2.2f+Random.value*1.8f)+Vector3.up*(1.8f+Random.value*2f);body.angularVelocity=Random.insideUnitSphere*8f;Destroy(shard,1.15f);}if(Alignment==ElementalAlignment.Storm)EmitStormDischarge(origin);else if(Alignment==ElementalAlignment.Earth)EmitEarthRupture(origin);else if(Alignment==ElementalAlignment.Venom)EmitVenomContamination(origin);}
    private void EmitStormDischarge(Vector3 origin){var branches=ImpactProfile==Profile.DeepColossus?7:4;var reach=ImpactProfile==Profile.DeepColossus?5.4f:3.6f;for(var i=0;i<branches;i++){var direction=Quaternion.Euler(0,(360f*i/branches)+Random.Range(-18f,18f),0)*Vector3.forward;var elbow=origin+direction*(reach*.48f)+Vector3.up*Random.Range(.08f,.35f);var end=origin+direction*reach+Vector3.up*.05f;CreateArc(origin+Vector3.up*.16f,elbow,.075f);CreateArc(elbow,end,.055f);if(i%2==0){var forkDirection=Quaternion.Euler(0,Random.Range(-32f,32f),0)*direction;CreateArc(elbow,elbow+forkDirection*(reach*.38f)+Vector3.up*Random.Range(.05f,.28f),.04f);}}}
    private void EmitEarthRupture(Vector3 origin){var fractures=ImpactProfile==Profile.DeepColossus?8:5;var reach=ImpactProfile==Profile.DeepColossus?6.2f:4.1f;for(var i=0;i<fractures;i++){var direction=Quaternion.Euler(0,360f*i/fractures+Random.Range(-12f,12f),0)*Vector3.forward;var mid=origin+direction*(reach*.52f)+Quaternion.Euler(0,90f,0)*direction*Random.Range(-.35f,.35f);var end=origin+direction*reach;CreateRupture(origin,mid,end);if(i%2==0)CreateEarthMass(mid,direction,ImpactProfile==Profile.DeepColossus?1.45f:1f);}CreateEarthMass(origin,Vector3.up,ImpactProfile==Profile.DeepColossus?1.8f:1.25f);}
    private void EmitVenomContamination(Vector3 origin){var pools=ImpactProfile==Profile.DeepColossus?9:6;var reach=ImpactProfile==Profile.DeepColossus?5.8f:3.9f;CreateVenomPool(origin,ImpactProfile==Profile.DeepColossus?1.7f:1.25f,2.8f);for(var i=0;i<pools;i++){var direction=Quaternion.Euler(0,360f*i/pools+Random.Range(-24f,24f),0)*Vector3.forward;var distance=Random.Range(reach*.38f,reach);var position=origin+direction*distance;CreateVenomPool(position,Random.Range(.55f,1.05f)*(ImpactProfile==Profile.DeepColossus?1.2f:1f),Random.Range(1.8f,2.65f));if(i%2==0)CreateVenomDroplet(origin+Vector3.up*.25f,direction,ImpactProfile==Profile.DeepColossus?1.25f:1f);}}
    private void CreateVenomPool(Vector3 position,float scale,float lifetime){var pool=GameObject.CreatePrimitive(PrimitiveType.Cylinder);pool.name="Magenheim_VenomContaminationPool";pool.transform.position=position+Vector3.up*.025f;pool.transform.localScale=new Vector3(scale,.012f,scale*Random.Range(.72f,1.12f));pool.transform.rotation=Quaternion.Euler(0,Random.Range(0f,360f),0);var c=pool.GetComponent<Collider>();if(c)Destroy(c);var r=pool.GetComponent<Renderer>();Material? material=null;if(r){material=new Material(Shader.Find("Standard"));material.color=new Color(.28f,.62f,.12f,.72f);material.SetFloat("_Metallic",.05f);material.SetFloat("_Glossiness",.18f);r.material=material;}var life=pool.AddComponent<VenomPoolLifetime>();life.Configure(material,lifetime);}
    private void CreateVenomDroplet(Vector3 origin,Vector3 direction,float scale){var droplet=GameObject.CreatePrimitive(PrimitiveType.Sphere);droplet.name="Magenheim_VenomCorrosiveDroplet";droplet.transform.position=origin;droplet.transform.localScale=Vector3.one*.12f*scale;var c=droplet.GetComponent<Collider>();if(c)Destroy(c);var r=droplet.GetComponent<Renderer>();Material? material=null;if(r){material=new Material(Shader.Find("Standard"));material.color=new Color(.42f,.82f,.16f,.9f);material.SetFloat("_Glossiness",.32f);r.material=material;}var body=droplet.AddComponent<Rigidbody>();body.mass=.025f;body.velocity=direction.normalized*Random.Range(1.6f,2.7f)+Vector3.up*Random.Range(2.1f,3.4f);var life=droplet.AddComponent<EarthMassLifetime>();life.Material=material;Destroy(droplet,1.1f);}
    private void CreateRupture(Vector3 start,Vector3 mid,Vector3 end){var rupture=new GameObject("Magenheim_EarthSeismicRupture");var line=rupture.AddComponent<LineRenderer>();var material=new Material(Shader.Find("Sprites/Default"));material.color=new Color(.34f,.23f,.12f,.9f);line.material=material;line.positionCount=3;line.SetPosition(0,start+Vector3.up*.025f);line.SetPosition(1,mid+Vector3.up*.025f);line.SetPosition(2,end+Vector3.up*.025f);line.startWidth=.16f;line.endWidth=.045f;line.useWorldSpace=true;var life=rupture.AddComponent<StormArcLifetime>();life.Material=material;Destroy(rupture,.42f);}
    private void CreateEarthMass(Vector3 position,Vector3 direction,float scale){var mass=GameObject.CreatePrimitive(PrimitiveType.Cube);mass.name="Magenheim_EarthDisplacedMass";mass.transform.position=position+Vector3.up*.08f;mass.transform.localScale=new Vector3(.42f,.24f,.42f)*scale;mass.transform.rotation=Random.rotation;var c=mass.GetComponent<Collider>();if(c)Destroy(c);var r=mass.GetComponent<Renderer>();Material? material=null;if(r){material=new Material(Shader.Find("Standard"));material.color=new Color(.31f,.22f,.13f,.95f);material.SetFloat("_Glossiness",.05f);r.material=material;}var body=mass.AddComponent<Rigidbody>();body.mass=.12f;body.velocity=(direction.normalized+Vector3.up*1.5f)*(1.1f+Random.value*.8f);body.angularVelocity=Random.insideUnitSphere*3f;var life=mass.AddComponent<EarthMassLifetime>();life.Material=material;Destroy(mass,.75f);}
    private void CreateArc(Vector3 start,Vector3 end,float width){var arc=new GameObject("Magenheim_StormImpactArc");var line=arc.AddComponent<LineRenderer>();var material=new Material(Shader.Find("Sprites/Default"));material.color=new Color(.58f,.72f,1f,.92f);line.material=material;line.positionCount=2;line.SetPosition(0,start);line.SetPosition(1,end);line.startWidth=width;line.endWidth=width*.35f;line.useWorldSpace=true;var life=arc.AddComponent<StormArcLifetime>();life.Material=material;Destroy(arc,.18f);}
    private sealed class HeavyImpactWave:MonoBehaviour{private float _speed,_life,_age;private Material? _material;internal void Configure(float speed,float life,Material? material){_speed=speed;_life=life;_material=material;}private void Update(){_age+=Time.deltaTime;var s=1f+_speed*Time.deltaTime;transform.localScale=new Vector3(transform.localScale.x*s,transform.localScale.y,transform.localScale.z*s);if(_age>=_life)Destroy(gameObject);}private void OnDestroy(){if(_material)Destroy(_material);}}
    private sealed class StormArcLifetime:MonoBehaviour{internal Material? Material;private void OnDestroy(){if(Material)Destroy(Material);}}
    private sealed class EarthMassLifetime:MonoBehaviour{internal Material? Material;private void OnDestroy(){if(Material)Destroy(Material);}}
    private sealed class VenomPoolLifetime:MonoBehaviour{private Material? _material;private float _life,_age;private Vector3 _baseScale;internal void Configure(Material? material,float life){_material=material;_life=life;_baseScale=transform.localScale;}private void Update(){_age+=Time.deltaTime;var t=Mathf.Clamp01(_age/_life);transform.localScale=new Vector3(_baseScale.x*(1f+t*.22f),_baseScale.y,_baseScale.z*(1f+t*.22f));if(_age>=_life)Destroy(gameObject);}private void OnDestroy(){if(_material)Destroy(_material);}}
}
