using System;using System.Collections.Generic;using BepInEx.Logging;using Jotunn.Entities;using Jotunn.Managers;using Magenheim.Core;using UnityEngine;namespace Magenheim.Runtime;
internal sealed class DeepFractureCreatureRegistrar:IDisposable{
 internal const string AnnoyanceWispPrefix="Magenheim_AnnoyanceWisp_",GeodeCrawlerPrefix="Magenheim_GeodeCrawler_",ShardlingPrefix="Magenheim_Shardling_",CrystalParasitePrefix="Magenheim_CrystalParasite_",CrystalRevenantPrefix="Magenheim_CrystalRevenant_",FacetSentryPrefix="Magenheim_FacetSentry_",StoneSentinelPrefix="Magenheim_StoneSentinel_",CrystalHoundPrefix="Magenheim_CrystalHound_",BurrowerPrefix="Magenheim_Burrower_",StoneGuardianPrefix="Magenheim_StoneGuardian_";
 private readonly ManualLogSource _log;private bool _subscribed,_registered;internal DeepFractureCreatureRegistrar(ManualLogSource log)=>_log=log??throw new ArgumentNullException(nameof(log));internal void Register(){if(_subscribed||_registered)return;PrefabManager.OnVanillaPrefabsAvailable+=RegisterContent;_subscribed=true;}
 private void RegisterContent(){if(_registered)return;try{var src=new[]{S("Wisp"),S("Tick"),S("Greydwarf"),S("Leech"),S("Draugr"),S("DvergerMage"),S("StoneGolem"),S("Fenring"),S("Seeker")};var r=new List<string>();foreach(ElementalAlignment a in Enum.GetValues(typeof(ElementalAlignment))){r.Add(R(src[0],a,AnnoyanceWispPrefix,"Annoyance Wisp",34,5.5f,2.5f,DeepFractureCreatureVisuals.ApplyAnnoyanceWisp));r.Add(R(src[1],a,GeodeCrawlerPrefix,"Geode Crawler",72,4,1.8f,DeepFractureCreatureVisuals.ApplyGeodeCrawler));r.Add(R(src[2],a,ShardlingPrefix,"Shardling",48,6.2f,2.8f,DeepFractureCreatureVisuals.ApplyShardling));r.Add(R(src[3],a,CrystalParasitePrefix,"Crystal Parasite",58,3.8f,1.6f,DeepFractureCreatureVisuals.ApplyCrystalParasite));r.Add(R(src[4],a,CrystalRevenantPrefix,"Crystal Revenant",118,4.6f,2.1f,DeepFractureCreatureVisuals.ApplyCrystalRevenant));r.Add(R(src[5],a,FacetSentryPrefix,"Facet Sentry",92,3.4f,1.4f,DeepFractureCreatureVisuals.ApplyFacetSentry));r.Add(R(src[6],a,StoneSentinelPrefix,"Stone Sentinel",260,3.1f,1.25f,DeepFractureCreatureVisuals.ApplyStoneSentinel));r.Add(R(src[7],a,CrystalHoundPrefix,"Crystal Hound",96,7.2f,3.1f,DeepFractureCreatureVisuals.ApplyCrystalHound));r.Add(R(src[8],a,BurrowerPrefix,"Burrower",132,5.4f,2.2f,DeepFractureCreatureVisuals.ApplyBurrower));r.Add(R(src[6],a,StoneGuardianPrefix,"Stone Guardian",440,2.7f,1.05f,DeepFractureCreatureVisuals.ApplyStoneGuardian));}_registered=true;_log.LogInfo($"Registered {r.Count} additive Deep Fracture creature variants: {string.Join(", ",r)}.");}catch(Exception e){_log.LogError($"Deep Fracture creature registration failed: {e}");throw;}finally{Dispose();}}
 private static GameObject S(string n){var s=PrefabManager.Instance.GetPrefab(n)??throw new InvalidOperationException($"Vanilla creature source '{n}' is unavailable; refusing to create an unverified chassis.");if(!s.GetComponent<Character>()||!s.GetComponent<BaseAI>()||!s.GetComponent<ZNetView>())throw new InvalidOperationException($"Vanilla creature source '{n}' lacks required Character/BaseAI/ZNetView behavior.");return s;}
 private static GameObject C(string n,GameObject s){if(PrefabManager.Instance.GetPrefab(n))throw new InvalidOperationException($"Cannot replace occupied Deep Fracture creature identity '{n}'.");var p=PrefabManager.Instance.CreateClonedPrefab(n,s)??throw new InvalidOperationException($"Unable to clone Deep Fracture creature host '{n}'.");p.name=n;if(!p.GetComponent<Character>()||!p.GetComponent<BaseAI>()||!p.GetComponent<ZNetView>())throw new InvalidOperationException($"Cloned Deep Fracture creature '{n}' lost required behavior.");return p;}
 private static string R(GameObject s,ElementalAlignment a,string prefix,string display,float hp,float run,float walk,Action<GameObject,ElementalAlignment> visual){var n=prefix+a,p=C(n,s);var ch=p.GetComponent<Character>();ch.m_name=$"{a} {display}";ch.m_health=hp;ch.m_runSpeed=Mathf.Max(ch.m_runSpeed,run);ch.m_walkSpeed=Mathf.Max(ch.m_walkSpeed,walk);visual(p,a);PrefabManager.Instance.AddPrefab(new CustomPrefab(p,true));return n;}
 public void Dispose(){if(!_subscribed)return;PrefabManager.OnVanillaPrefabsAvailable-=RegisterContent;_subscribed=false;}}
