using System;using System.Collections.Generic;using System.Linq;using Magenheim.Core;using UnityEngine;namespace Magenheim.Runtime;
internal static class DeepFractureCreatureVisuals{
 private static readonly Dictionary<int,Mesh> PrismMeshes=new();
 internal static void ApplyAnnoyanceWisp(GameObject p,ElementalAlignment a){var c=B(p,"annoyance-wisp",a);P(c,"motion-core",Vector3.zero,.22f,.58f,7,c.Core);P(c,"crystal-shell",Vector3.zero,.38f,.82f,7,c.Shell);for(int i=0;i<5;i++){float x=Mathf.PI*2*i/5+.28f;P(c,"orbit-shard-"+i,new Vector3(Mathf.Cos(x)*.48f,0,Mathf.Sin(x)*.48f),.075f,.3f,5,c.Shard);}F(p,c,3.2f,.85f);}
 internal static void ApplyGeodeCrawler(GameObject p,ElementalAlignment a){var c=B(p,"geode-crawler",a);c.Root.transform.localPosition=new Vector3(0,.08f,0);P(c,"stone-abdomen",new Vector3(0,.12f,-.18f),.43f,.72f,8,c.Shell,new Vector3(90,0,0));P(c,"stone-thorax",new Vector3(0,.12f,.34f),.32f,.48f,7,c.Shell,new Vector3(90,0,0));P(c,"carapace-core",new Vector3(0,.39f,-.12f),.23f,.38f,6,c.Core);for(int i=0;i<3;i++){float z=-.27f+i*.3f;P(c,"left-leg-"+i,new Vector3(-.43f,-.04f,z),.075f,.58f,5,c.Shard,new Vector3(0,0,62));P(c,"right-leg-"+i,new Vector3(.43f,-.04f,z),.075f,.58f,5,c.Shard,new Vector3(0,0,-62));}F(p,c,2.4f,.55f);}
 internal static void ApplyShardling(GameObject p,ElementalAlignment a){var c=B(p,"shardling",a);c.Root.transform.localPosition=new Vector3(0,.76f,0);P(c,"locomotion-core",new Vector3(0,.12f,0),.19f,.48f,6,c.Core);P(c,"torso",new Vector3(0,.34f,0),.29f,.82f,5,c.Shell);P(c,"head",new Vector3(0,.87f,0),.21f,.47f,5,c.Shard);P(c,"left-blade",new Vector3(-.39f,.33f,0),.075f,.76f,5,c.Shard,new Vector3(0,0,-31));P(c,"right-blade",new Vector3(.39f,.33f,0),.075f,.76f,5,c.Shard,new Vector3(0,0,31));P(c,"left-runner",new Vector3(-.18f,-.37f,0),.085f,.86f,5,c.Shell);P(c,"right-runner",new Vector3(.18f,-.37f,0),.085f,.86f,5,c.Shell);F(p,c,2.1f,.42f);}
 internal static void ApplyCrystalParasite(GameObject p,ElementalAlignment a){var c=B(p,"crystal-parasite",a);c.Root.transform.localPosition=new Vector3(0,.18f,0);P(c,"regrowth-core",new Vector3(0,.24f,-.08f),.25f,.54f,7,c.Core,new Vector3(88,0,0));for(int i=0;i<5;i++)P(c,"body-"+i,new Vector3(0,.05f,-.52f+i*.25f),.29f-i*.018f,.32f,7,c.Shell,new Vector3(90,0,0));for(int i=0;i<4;i++){float z=-.38f+i*.27f;P(c,"left-hook-"+i,new Vector3(-.3f,-.08f,z),.055f,.42f,4,c.Shard,new Vector3(0,0,66));P(c,"right-hook-"+i,new Vector3(.3f,-.08f,z),.055f,.42f,4,c.Shard,new Vector3(0,0,-66));}F(p,c,2.6f,.62f);}
 internal static void ApplyCrystalRevenant(GameObject p,ElementalAlignment a){var c=B(p,"crystal-revenant",a);c.Root.transform.localPosition=new Vector3(0,1.05f,0);P(c,"resistance-core",new Vector3(0,.38f,-.12f),.25f,.55f,7,c.Core);P(c,"armored-torso",new Vector3(0,.42f,0),.48f,1.08f,7,c.Shell);P(c,"helmet",new Vector3(0,1.18f,0),.34f,.55f,6,c.Shell);P(c,"armor-core-left",new Vector3(-.45f,.58f,0),.16f,.46f,6,c.Core);P(c,"armor-core-right",new Vector3(.45f,.58f,0),.16f,.46f,6,c.Core);P(c,"left-arm",new Vector3(-.58f,.12f,0),.13f,.95f,6,c.Shell);P(c,"right-arm",new Vector3(.58f,.12f,0),.13f,.95f,6,c.Shell);P(c,"left-leg",new Vector3(-.22f,-.62f,0),.15f,1.05f,6,c.Shell);P(c,"right-leg",new Vector3(.22f,-.62f,0),.15f,1.05f,6,c.Shell);F(p,c,3.4f,.7f);}
 internal static void ApplyFacetSentry(GameObject p,ElementalAlignment a){var c=B(p,"facet-sentry",a);c.Root.transform.localPosition=new Vector3(0,1.15f,0);P(c,"control-core",new Vector3(0,.48f,0),.31f,.72f,8,c.Core);P(c,"lower-pedestal",new Vector3(0,-.42f,0),.44f,1.05f,8,c.Shell);P(c,"upper-pedestal",new Vector3(0,.22f,0),.38f,.7f,8,c.Shell);P(c,"sensor-head",new Vector3(0,.96f,0),.42f,.58f,6,c.Shard);P(c,"forward-facet",new Vector3(0,.96f,.39f),.16f,.43f,5,c.Core,new Vector3(82,0,0));for(int i=0;i<6;i++){float x=Mathf.PI*2*i/6;P(c,"control-prong-"+i,new Vector3(Mathf.Cos(x)*.48f,.55f,Mathf.Sin(x)*.48f),.065f,.58f,5,c.Shard,new Vector3(-38,0,-Mathf.Cos(x)*20));}P(c,"left-stabilizer",new Vector3(-.5f,-.38f,0),.11f,.75f,6,c.Shell,new Vector3(0,0,-52));P(c,"right-stabilizer",new Vector3(.5f,-.38f,0),.11f,.75f,6,c.Shell,new Vector3(0,0,52));F(p,c,4.2f,.95f);}
 private sealed record V(GameObject Root,Renderer[] Original,Color Tint,Material Shell,Material Core,Material Shard);private static V B(GameObject p,string f,ElementalAlignment a){var o=p.GetComponentsInChildren<Renderer>(true);var s=o.Select(r=>r.sharedMaterial).FirstOrDefault(m=>m)??throw new InvalidOperationException($"Creature host '{p.name}' exposes no material source.");var root=new GameObject("magenheim.fracture.creature."+f+".visual"){layer=p.layer};root.transform.SetParent(p.transform,false);var t=ElementVisualPalette.Tint(a);return new V(root,o,t,M(s,f+".shell",Color.Lerp(t,new Color(.28f,.25f,.22f),.62f),.18f,.58f,.18f),M(s,f+".core",Color.Lerp(t,Color.white,.68f),.02f,.96f,1.35f),M(s,f+".shard",t,.05f,.78f,.82f));}
 private static void F(GameObject p,V c,float range,float intensity){var l=c.Root.AddComponent<Light>();l.color=c.Tint;l.range=range;l.intensity=intensity;foreach(var r in c.Original)if(!r.transform.IsChildOf(c.Root.transform))r.enabled=false;foreach(var lod in p.GetComponentsInChildren<LODGroup>(true))lod.enabled=false;}
 private static Material M(Material s,string n,Color c,float metal,float gloss,float e){var m=new Material(s){name="magenheim.fracture.creature."+n};m.mainTexture=Texture2D.whiteTexture;if(m.HasProperty("_Color"))m.SetColor("_Color",c);if(m.HasProperty("_Metallic"))m.SetFloat("_Metallic",metal);if(m.HasProperty("_Glossiness"))m.SetFloat("_Glossiness",gloss);if(m.HasProperty("_EmissionColor")){m.SetColor("_EmissionColor",c*e);m.EnableKeyword("_EMISSION");}m.SetOverrideTag("RenderType","Opaque");if(m.HasProperty("_ZWrite"))m.SetFloat("_ZWrite",1);m.renderQueue=2000;return m;}
 private static void P(V c,string name,Vector3 pos,float radius,float height,int sides,Material mat,Vector3? rot=null){if(!PrismMeshes.TryGetValue(sides,out var mesh)){mesh=Mesh(sides);PrismMeshes.Add(sides,mesh);}var x=new GameObject(name){layer=c.Root.layer};x.transform.SetParent(c.Root.transform,false);x.transform.localPosition=pos;x.transform.localRotation=Quaternion.Euler(rot??Vector3.zero);x.transform.localScale=new Vector3(radius*2,height,radius*2);x.AddComponent<MeshFilter>().sharedMesh=mesh;x.AddComponent<MeshRenderer>().sharedMaterial=mat;}
 private static Mesh Mesh(int sides){var v=new List<Vector3>();var t=new List<int>();for(int i=0;i<sides;i++){float a=2*Mathf.PI*i/sides;v.Add(new Vector3(.36f*Mathf.Cos(a),-.45f,.36f*Mathf.Sin(a)));}for(int i=0;i<sides;i++){float a=2*Mathf.PI*i/sides;v.Add(new Vector3(.5f*Mathf.Cos(a),.2f,.5f*Mathf.Sin(a)));}int top=v.Count;v.Add(new Vector3(0,.68f,0));int bottom=v.Count;v.Add(new Vector3(0,-.5f,0));for(int i=0;i<sides;i++){int n=(i+1)%sides;t.AddRange(new[]{bottom,n,i,i,n,sides+i,n,sides+n,sides+i,sides+i,sides+n,top});}var m=new Mesh{name="magenheim.fracture.creature.prism."+sides,vertices=v.ToArray(),triangles=t.ToArray()};m.RecalculateNormals();m.RecalculateBounds();return m;}}
