using System;
using UnityEngine;

namespace Magenheim.Runtime
{
    internal static class DeepFractureLegacyCoreBinder
    {
        internal static void BindAnnoyanceWisp(GameObject prefab){var c=Context(prefab,"Annoyance Wisp","magenheim.fracture.creature.annoyance-wisp.visual");Attach(c.Root,"motion-core",c.Owner,c.View,"movement",DeepFractureCrystalFunction.Movement,42f);}
        internal static void BindGeodeCrawler(GameObject prefab){var c=Context(prefab,"Geode Crawler","magenheim.fracture.creature.geode-crawler.visual");Attach(c.Root,"carapace-core",c.Owner,c.View,"armor",DeepFractureCrystalFunction.Armor,68f);}
        internal static void BindShardling(GameObject prefab){var c=Context(prefab,"Shardling","magenheim.fracture.creature.shardling.visual");Attach(c.Root,"locomotion-core",c.Owner,c.View,"movement",DeepFractureCrystalFunction.Movement,52f);}
        internal static void BindStoneGuardian(GameObject prefab){BindDefensiveTriad(prefab,"Stone Guardian","magenheim.fracture.creature.stone-guardian.visual","resistance-core","armor-core-left","armor-core-right",260f,220f);}
        internal static void BindStoneSentinel(GameObject prefab){BindDefensiveTriad(prefab,"Stone Sentinel","magenheim.fracture.creature.stone-sentinel.visual","resistance-core","armor-core-left","armor-core-right",190f,165f);}
        internal static void BindCrystalRevenant(GameObject prefab){BindDefensiveTriad(prefab,"Crystal Revenant","magenheim.fracture.creature.crystal-revenant.visual","resistance-core","armor-core-l","armor-core-r",115f,90f);}
        internal static void BindCrystalHound(GameObject prefab){var c=Context(prefab,"Crystal Hound","magenheim.fracture.creature.crystal-hound.visual");Attach(c.Root,"motion-core",c.Owner,c.View,"movement",DeepFractureCrystalFunction.Movement,105f);Attach(c.Root,"resistance-core",c.Owner,c.View,"resistance",DeepFractureCrystalFunction.Resistance,85f);}
        internal static void BindBurrower(GameObject prefab){var c=Context(prefab,"Burrower","magenheim.fracture.creature.burrower.visual");Attach(c.Root,"burrow-core",c.Owner,c.View,"burrow",DeepFractureCrystalFunction.Burrow,145f);Attach(c.Root,"armor-core",c.Owner,c.View,"armor",DeepFractureCrystalFunction.Armor,120f);}
        internal static void BindCrystalParasite(GameObject prefab){var c=Context(prefab,"Crystal Parasite","magenheim.fracture.creature.crystal-parasite.visual");Attach(c.Root,"regrowth-core",c.Owner,c.View,"regeneration",DeepFractureCrystalFunction.Regeneration,70f);}
        internal static void BindFacetSentry(GameObject prefab){var c=Context(prefab,"Facet Sentry","magenheim.fracture.creature.facet-sentry.visual");Attach(c.Root,"control-core",c.Owner,c.View,"environmental_control",DeepFractureCrystalFunction.EnvironmentalControl,125f);}
        private static void BindDefensiveTriad(GameObject prefab,string displayName,string rootName,string resistanceName,string leftArmorName,string rightArmorName,float resistanceHealth,float armorHealth){var c=Context(prefab,displayName,rootName);Attach(c.Root,resistanceName,c.Owner,c.View,"resistance",DeepFractureCrystalFunction.Resistance,resistanceHealth);Attach(c.Root,leftArmorName,c.Owner,c.View,"armor_left",DeepFractureCrystalFunction.Armor,armorHealth);Attach(c.Root,rightArmorName,c.Owner,c.View,"armor_right",DeepFractureCrystalFunction.Armor,armorHealth);}
        private sealed class BindingContext{internal readonly Transform Root;internal readonly Character Owner;internal readonly ZNetView View;internal BindingContext(Transform root,Character owner,ZNetView view){Root=root;Owner=owner;View=view;}}
        private static BindingContext Context(GameObject prefab,string displayName,string rootName){if(prefab==null)throw new ArgumentNullException(nameof(prefab));var owner=prefab.GetComponent<Character>()??throw new InvalidOperationException(displayName+" host has no Character.");var view=prefab.GetComponent<ZNetView>()??throw new InvalidOperationException(displayName+" host has no ZNetView.");return new BindingContext(Find(prefab.transform,rootName),owner,view);}
        private static void Attach(Transform root,string name,Character owner,ZNetView view,string id,DeepFractureCrystalFunction function,float health){var part=Find(root,name);if(part.GetComponent<DeepFractureCrystalComponent>()!=null)throw new InvalidOperationException("Duplicate Deep Fracture crystal binding on '"+name+"'.");DeepFractureCrystalComponent.Attach(part.gameObject,owner,view,id,function,health);}
        private static Transform Find(Transform root,string name){if(root.name==name)return root;for(var i=0;i<root.childCount;i++){var match=TryFind(root.GetChild(i),name);if(match!=null)return match;}throw new InvalidOperationException("Required Deep Fracture visual part '"+name+"' is missing.");}
        private static Transform? TryFind(Transform root,string name){if(root.name==name)return root;for(var i=0;i<root.childCount;i++){var match=TryFind(root.GetChild(i),name);if(match!=null)return match;}return null;}
    }
}