// Generated by tools/author-underworld-donor-armour.py. Donor geometry is retained.
using System;
using UnityEngine;
namespace Magenheim.Runtime;
internal static class UnderworldDonorArmourProfiles
{
    internal static Color Tint(string modelId)
    {
        if(modelId.StartsWith("underworld-armor-sporeweave-", StringComparison.Ordinal)) return new Color(0.64f,0.9f,0.7f,1f);
        if(modelId.StartsWith("underworld-armor-palewater-", StringComparison.Ordinal)) return new Color(0.68f,0.9f,1.0f,1f);
        if(modelId.StartsWith("underworld-armor-emberiron-", StringComparison.Ordinal)) return new Color(0.9f,0.62f,0.4f,1f);
        if(modelId.StartsWith("underworld-armor-rimeward-", StringComparison.Ordinal)) return new Color(0.72f,0.85f,1.0f,1f);
        if(modelId.StartsWith("underworld-armor-stoneanchor-", StringComparison.Ordinal)) return new Color(0.72f,0.7f,0.82f,1f);
        if(modelId.StartsWith("underworld-armor-defiant-", StringComparison.Ordinal)) return new Color(1.0f,0.72f,0.45f,1f);
        throw new InvalidOperationException("Unknown native armour palette: " + modelId);
    }
}
